# GitHub Funding configuration — keep only GitHub Sponsors
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-funding-for-your-repository

github: WanionCane