package tech.wanion.encryptable.util

import at.favre.lib.hkdf.HKDF
import tech.wanion.encryptable.util.extensions.markForWiping

/**
 * Utility object for deriving cryptographic keys from high-entropy strings using HKDF.
 * Provides methods for deterministic key derivation.
 */
object HKDF {
    /**
     * Derives a deterministic cryptographic key from a high-entropy input using HKDF with HMAC-SHA256.
     * @param entropy The high-entropy input string.
     * @param source The context or class for key derivation.
     * @param context REQUIRED context string to ensure independent derivations (e.g., "CID", "ENCRYPTION_KEY").
     *                This prevents different uses of HKDF from producing related outputs.
     * @param byteLength The desired key length in bytes (default 32).
     * @return The derived key as a byte array.
     */
    @JvmStatic
    fun deriveFromEntropy(entropy: String, source: Any, context: String, byteLength: Int = 32): ByteArray {
        require(context.isNotBlank()) { "Context parameter must not be blank. Use a specific context like 'CID' or 'ENCRYPTION_KEY' to ensure cryptographic independence." }

        // Input Key Material (IKM): The high-entropy string generated by SecureRandom.
        val highEntropyBytes = entropy.toByteArray()

        // **BREAKING CHANGE (v1.1.0):** Prior to 1.1.0, sourceInfo was derived from source.toString(),
        // which produced unwanted prefixes like "class " when applied to Class objects.
        // This has been replaced with explicit type-based logic to ensure clean, consistent values:
        // - For Class<?> objects: use the fully qualified class name (without "class " prefix)
        // - For String objects: use the string directly
        // - For all other objects: use their class's fully qualified name
        // This change is incompatible with all previous versions and represents the first true breaking change.
        val sourceInfo = when(source) {
            is Class<*> -> source.name
            is String -> source
            else -> source::class.java.name
        }
        val info = "$sourceInfo:$context"

        // Initializes the Key Derivation Function (HKDF) with HMAC-SHA256.
        // SHA-256 is hardware accelerated on modern CPUs
        // (Intel SHA Extensions, ARM Crypto Extensions), providing significantly better performance
        // without sacrificing security. Both SHA-256 and SHA-512 are cryptographically secure for HKDF.
        val hkdf = HKDF.fromHmacSha256()

        // Expands the high-entropy input using the context info.
        // Since the input is already high-entropy, we skip the extract step per RFC 5869.
        // The resulting key is 32 bytes long (256 bits), which is suitable for AES-256.
        val derivedKey = hkdf.expand(highEntropyBytes, info.toByteArray(), byteLength)

        // Marks sensitive data for secure wiping from memory.
        markForWiping(entropy, highEntropyBytes, derivedKey)

        return derivedKey
    }
}