package tech.wanion.encryptable.util

import at.favre.lib.hkdf.HKDF
import tech.wanion.encryptable.util.extensions.markForWiping

/**
 * Utility object for deriving cryptographic keys from high-entropy strings using HKDF.
 * Provides methods for deterministic key derivation.
 */
object HKDF {
    /**
     * Derives a deterministic cryptographic key from a high-entropy input using HKDF with HMAC-SHA256.
     * @param entropy The high-entropy input string.
     * @param source The context or class for key derivation.
     * @param context REQUIRED context string to ensure independent derivations (e.g., "CID", "ENCRYPTION_KEY").
     *                This prevents different uses of HKDF from producing related outputs.
     * @param byteLength The desired key length in bytes (default 32).
     * @return The derived key as a byte array.
     */
    @JvmStatic
    fun deriveFromEntropy(entropy: String, source: Any, context: String, byteLength: Int = 32): ByteArray {
        require(context.isNotBlank()) { "Context parameter must not be blank. Use a specific context like 'CID' or 'ENCRYPTION_KEY' to ensure cryptographic independence." }

        // Input Key Material (IKM): The high-entropy string generated by SecureRandom.
        val highEntropyBytes = entropy.toByteArray()

        // The salt is deterministically derived from the high-entropy input.
        // This is safe because the input itself provides a high degree of uniqueness
        // and entropy, and this is a standard pattern for deterministic HKDF usage
        // when expanding a high-quality key.

        // Context info for HKDF to ensure different derivations are independent.
        val sourceInfo = when(source) {
            is Class<*> -> source.toString()
            is String -> source
            else -> source::class.java.toString()
        }
        val info = "$sourceInfo:$context"

        // Initializes the Key Derivation Function (HKDF) with HMAC-SHA256.
        // SHA-256 is hardware accelerated on modern CPUs
        // (Intel SHA Extensions, ARM Crypto Extensions), providing significantly better performance
        // without sacrificing security. Both SHA-256 and SHA-512 are cryptographically secure for HKDF.
        val hkdf = HKDF.fromHmacSha256()

        // Extracts and expands the key using the salt, IKM, and context info.
        // The resulting key is 32 bytes long (256 bits), which is suitable for AES-256.
        val derivedKey = hkdf.expand(highEntropyBytes, info.toByteArray(), byteLength)

        // Marks sensitive data for secure wiping from memory.
        markForWiping(entropy, highEntropyBytes, derivedKey)

        return derivedKey
    }
}