package tech.wanion.encryptable.util

import at.favre.lib.hkdf.HKDF
import tech.wanion.encryptable.util.extensions.markForWiping

/**
 * Utility object for deriving cryptographic keys from high-entropy strings using HKDF.
 * Provides methods for deterministic key derivation.
 */
object HKDF {
    /**
     * Derives a deterministic cryptographic key from a high-entropy input using HKDF with HMAC-SHA256.
     * @param entropy The high-entropy input string.
     * @param source The context or class for key derivation.
     * @param context REQUIRED context string to ensure independent derivations (e.g., "CID", "ENCRYPTION_KEY").
     *                This prevents different uses of HKDF from producing related outputs.
     * @param byteLength The desired key length in bytes (default 32).
     * @return The derived key as a byte array.
     */
    @JvmStatic
    fun deriveFromEntropy(entropy: String, source: Any, context: String, byteLength: Int = 32): ByteArray {
        require(context.isNotBlank()) { "Context parameter must not be blank. Use a specific context like 'CID' or 'ENCRYPTION_KEY' to ensure cryptographic independence." }

        // Input Key Material (IKM): The high-entropy string generated by SecureRandom.
        val highEntropyBytes = entropy.toByteArray()

        // **BREAKING CHANGE (v1.1.0):** Prior to 1.1.0, sourceInfo was derived from source.toString(),
        // which produced unwanted prefixes like "class " when applied to Class objects.
        // This has been replaced with explicit type-based logic to ensure clean, consistent values:
        // - For Class<?> objects: use the fully qualified class name (without "class " prefix)
        // - For String objects: use the string directly
        // - For all other objects: use their class's fully qualified name
        // This change is incompatible with all previous versions and represents the first true breaking change.
        val sourceInfo = when(source) {
            is Class<*> -> source.name
            is String -> source
            else -> source::class.java.name
        }
        val info = "$sourceInfo:$context"

        // Initializes the Key Derivation Function (HKDF) with HMAC-SHA256.
        // SHA-256 is hardware accelerated on modern CPUs
        // (Intel SHA Extensions, ARM Crypto Extensions), providing significantly better performance
        // without sacrificing security. Both SHA-256 and SHA-512 are cryptographically secure for HKDF.
        val hkdf = HKDF.fromHmacSha256()

        // Expands the high-entropy input using the context info.
        //
        // **Why expand-only (no extract step)?**
        //
        // RFC 5869, Section 3.3 explicitly states:
        //   "In some applications, the input key material IKM may already be present as a
        //    cryptographically strong key [...]. In this case, the 'extract' step is unnecessary
        //    and can be skipped."
        //
        // The IKM passed to this method is always at least length-validated:
        //   - @HKDFId secrets: ≥48 chars (length only — entropy is NOT enforced, because user-credential-derived
        //     secrets, e.g. a combination of password + 2FA + username, cannot be guaranteed to always produce
        //     high-entropy values; the framework documents this as an accepted limitation)
        //   - Master secret: ≥74 user-provided chars validated at ≥3.5 bits/char (≥259 bits) by SecurityUtils
        //
        // The extract step (HKDF-Extract) exists to "condition" low-quality IKM (e.g., a Diffie-Hellman
        // shared secret or a human password) into a uniformly random PRK. However, extract does NOT add
        // entropy — it only redistributes existing entropy into a more uniform form. If the IKM has low
        // entropy, the derived key's security is bounded by that entropy regardless of whether extract
        // is used or not. Extract is therefore not a remedy for low-entropy input.
        //
        // **Determinism requirement:**
        // CID derivation MUST be deterministic — the same secret MUST always produce the same CID
        // to allow stateless database lookups. The full extract+expand pipeline would also be
        // deterministic (HKDF is a PRF), so this is not the deciding factor — but it reinforces
        // that any change to the derivation pipeline would be a BREAKING CHANGE:
        // all existing CIDs and ciphertext would become unreachable (different derived keys = data loss).
        //
        // **Breaking change warning:**
        // Switching from expand-only to extract+expand would silently produce different keys for all
        // existing data — CIDs would change (lookups fail), encryption keys would change (decryption fails).
        // There is no migration path. DO NOT change this without a full database re-encryption migration.
        val derivedKey = hkdf.expand(highEntropyBytes, info.toByteArray(), byteLength)

        // Marks sensitive data for secure wiping from memory.
        markForWiping(entropy, highEntropyBytes, derivedKey)

        return derivedKey
    }
}